export const tutors = [
    {
        name: "Muhammad Irfan",
        qualification: "Certified Tajweed Instructor",
        specialization: "Nazra & Hifz",
        experience: "8 Years",
        rating: 4.9,
        image: "https://ui-avatars.com/api/?name=Muhammad+Irfan&background=0D8ABC&color=fff",
        meetingLink: "https://zoom.us/j/1234567890",
    },
    {
        name: "Muhammad Imran",
        qualification: "Alim Course Graduate",
        specialization: "Fiqh & Islamic Studies",
        experience: "10 Years",
        rating: 4.8,
        image: "https://ui-avatars.com/api/?name=Muhammad+Imran&background=0D8ABC&color=fff",
        meetingLink: "https://zoom.us/j/1234567890",
    },
    {
        name: "Muhammad Ahmad",
        qualification: "Ijazah in Hafs",
        specialization: "Advanced Tajweed",
        experience: "12 Years",
        rating: 5.0,
        image: "https://ui-avatars.com/api/?name=Muhammad+Ahmad&background=0D8ABC&color=fff",
        meetingLink: "https://zoom.us/j/1234567890",
    },
    {
        name: "Muhammad Fayyaz",
        qualification: "Hafiz-e-Quran",
        specialization: "Hifz & Revision",
        experience: "15 Years",
        rating: 4.9,
        image: "https://ui-avatars.com/api/?name=Muhammad+Fayyaz&background=0D8ABC&color=fff",
        meetingLink: "https://zoom.us/j/1234567890",
    },
    {
        name: "Muhammad Kamil",
        qualification: "Masters in Arabic",
        specialization: "Arabic Language",
        experience: "7 Years",
        rating: 4.7,
        image: "https://ui-avatars.com/api/?name=Muhammad+Kamil&background=0D8ABC&color=fff",
        meetingLink: "https://zoom.us/j/1234567890",
    },
    {
        name: "Sumaira Younus",
        qualification: "Alima & Hafiza",
        specialization: "Quran Reading & Tajweed",
        experience: "9 Years",
        rating: 4.9,
        image: "https://ui-avatars.com/api/?name=Sumaira+Younus&background=E91E63&color=fff",
        meetingLink: "https://zoom.us/j/1234567890",
    },
    {
        name: "Aiman Khan",
        qualification: "Certified Quran Tutor",
        specialization: "Kids Quran Teaching",
        experience: "5 Years",
        rating: 4.8,
        image: "https://ui-avatars.com/api/?name=Aiman+Khan&background=E91E63&color=fff",
        meetingLink: "https://zoom.us/j/1234567890",
    },
    {
        name: "Qaria Rimsha",
        qualification: "Ijazah in Tajweed",
        specialization: "Advanced Tajweed (Ladies)",
        experience: "8 Years",
        rating: 5.0,
        image: "https://ui-avatars.com/api/?name=Qaria+Rimsha&background=E91E63&color=fff",
        meetingLink: "https://zoom.us/j/1234567890",
    },
    {
        name: "Dua Fatima",
        qualification: "Islamic Scholar",
        specialization: "Tafseer & Hadith",
        experience: "6 Years",
        rating: 4.8,
        image: "https://ui-avatars.com/api/?name=Dua+Fatima&background=E91E63&color=fff",
        meetingLink: "https://zoom.us/j/1234567890",
    },
    {
        name: "Sumaira Manzoor",
        qualification: "Hafiza",
        specialization: "Hifz for Girls",
        experience: "11 Years",
        rating: 4.9,
        image: "https://ui-avatars.com/api/?name=Sumaira+Manzoor&background=E91E63&color=fff",
        meetingLink: "https://zoom.us/j/1234567890",
    },
    {
        name: "Zahida Parveen",
        qualification: "Senior Quran Teacher",
        specialization: "Adult Quran Reading",
        experience: "20 Years",
        rating: 5.0,
        image: "https://ui-avatars.com/api/?name=Zahida+Parveen&background=E91E63&color=fff",
        meetingLink: "https://zoom.us/j/1234567890",
    },
    {
        name: "Qaria Shahida",
        qualification: "Expert Reciter",
        specialization: "Qirat & Tajweed",
        experience: "14 Years",
        rating: 4.9,
        image: "https://ui-avatars.com/api/?name=Qaria+Shahida&background=E91E63&color=fff",
        meetingLink: "https://zoom.us/j/1234567890",
    },
]
